"""add subscribers table

Revision ID: 27347ccc57a4
Revises: 470e3a53ca60
Create Date: 2021-03-08 12:50:06.231408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27347ccc57a4'
down_revision = '470e3a53ca60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
