"""add columns to admins table

Revision ID: 41fbb212e440
Revises: 061b2ae84b5c
Create Date: 2021-03-08 13:43:29.628679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fbb212e440'
down_revision = '061b2ae84b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('name', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('prof_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'prof_pic_path')
    op.drop_column('admins', 'name')
    op.drop_column('admins', 'bio')
    # ### end Alembic commands ###
