"""add post_pic_path column to posts table

Revision ID: daba50472177
Revises: 41fbb212e440
Create Date: 2021-03-08 14:42:26.591529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daba50472177'
down_revision = '41fbb212e440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_pic_path')
    # ### end Alembic commands ###
